# 6. Sistemas de ecuaciones

# Introducción

## Modelos lineales en economía e ingeniería

A finales del verano de 1949 Wassily Leontief, profesor de Harvard, introdujo cuidadosamente la última de sus tarjetas perforadas en la computadora de la universidad, la Mark II.  
Las tarjetas contenían información acerca de la economía de Estados Unidos, y representaban un resumen de más de 250.000 piezas de información producidas por la oficina encargada de las estadísticas laborales en Estados Unidos después de dos años de trabajo intenso.  
Leontief había dividido la economía de Estados Unidos en 500 “sectores”, tales como la industria del carbón, la industria automotriz, las comunicaciones, etc.  
Para cada sector, escribió una ecuación lineal que describía la forma en que dicho sector distribuía sus salidas hacia otros sectores de la economía.  
Debido a que la Mark II, una de las computadoras más grandes de la época, no podía manejar el sistema resultante de 500 ecuaciones y 500 incógnitas, Leontief había condensado el problema en un sistema de 42 ecuaciones y 42 incógnitas.  
La programación de la computadora Mark II para las 42 ecuaciones de Leontief requirió varios meses de esfuerzo, y él estaba ansioso por ver cuánto tiempo le tomaría a la máquina resolver el problema. La Mark II trabajó durante 56 horas hasta que finalmente produjo una solución.  
Leontief, quien recibió el Premio Nobel de Economía en 1973, abrió la puerta a una nueva era en el modelado matemático de la economía. Sus esfuerzos desplegados en Harvard en 1949 marcaron uno de los primeros usos significativos de las computadoras para analizar lo que entonces era un modelo matemático a gran escala.  
Desde entonces, los investigadores de muchos otros campos han empleado computadoras para analizar modelos matemáticos.  
Debido a las masivas cantidades de datos involucrados, por lo general, los modelos son lineales, esto es, se describen mediante sistemas de ecuaciones lineales.  
La importancia del álgebra lineal para las aplicaciones se ha elevado en proporción directa al aumento del poder de las computadoras, cada nueva generación de equipo y programas de cómputo dispara una demanda de capacidades aún mayores.  
Por lo tanto, la ciencia de las computadoras está sólidamente ligada al álgebra lineal mediante el crecimiento explosivo de los procesamientos paralelos de datos y los cálculos a gran escala.  
Los cientficos e ingenieros trabajan ahora en problemas mucho más complejos de lo que creían posible hace unas cuantas décadas.  
En la actualidad, el álgebra lineal tiene para los estudiantes universitarios un mayor valor potencial en muchos campos científicos y de negocios que cualquier otra materia de matemáticas.  
Aunque ya hemos visto algunos ejemplos, otros ejemplos del uso del álgebra lineal:
* **Exploración petrolera.** Cuando un barco busca depósitos submarinos de petróleo, diariamente sus computadoras resuelven miles de sistemas de ecuaciones lineales por separado. La información sísmica para elaborar las ecuaciones se obtiene a partir de ondas de choque submarinas creadas mediante explosiones con pistolas de aire. Las ondas rebotan en las rocas que hay bajo la supeficie marina y se miden empleando geófonos conectados a extensos cables instalados debajo del barco.  
* **Programación lineal.** En la actualidad, muchas decisiones administrativas importantes se toman con base en modelos de programación lineal que utilizan cientos de variables. Por ejemplo, la industria de las aerolíneas emplea programas lineales para crear los itinerarios de las tripulaciones de vuelo, monitorear las ubicaciones de los aviones, o planear los diversos programas de servicios de apoyo como mantenimiento y operaciones en terminal.
* **Redes eléctricas.** Los ingenieros utilizan programas de cómputo de simulación para diseñar circuitos eléctricos y microchips que incluyen millones de transistores. Estos programas utilizan técnicas de álgebra lineal y sistemas de ecuaciones lineales.

## ¿Qué es un sistema de ecuaciones lineales?  

Dados a<sub>ij</sub>, b<sub>i</sub> escalares, un sistema de ecuaciones lineales:
> $a_{11}\cdot x_1+a_{12}\cdot x_2+...+a_{1n}\cdot x_n=b_1$  
> $a_{21}\cdot x_1+a_{22}\cdot x_2+...+a_{1n}\cdot x_n=b_2$  
> ...  
> $a_{m1}\cdot x_1+a_{m2}\cdot x_2+...+a_{mn}\cdot x_n=b_m$  

Se llama **matriz de coeficientes** a:  
> M=$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)$ 
  
y matriz ampliada a:  
> M*=$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n} & b_1\\
   a_{21} & a_{22} & ... & a_{2n} & b_2\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn} & b_3\\
  \end{array} } \right)$  

* El sistema de ecuaciones será **compatible** (tiene solución) si detM=detM*
> Compatible determinado (tiene una única solución) si detM=detM* =n  
> Compatible indeterminado (tiene infinitas soluciones) si detM=detM* <n

* El sistema de ecuaciones será **incompatible** (no tiene solución) si detM≠detM*  

<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.  </style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [44]:
import numpy as np
A=([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
detA=np.linalg.det(A)
detA

1.9999999999999998

In [45]:
import numpy as np
B=([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])
detB=np.linalg.det(B)
detB

LinAlgError: Last 2 dimensions of the array must be square

<span style="color:orange">Anda! No se puede....Claro! Porque el determinante sólo existe para matrices cuadradas y ésta tiene dimensión 3x4.  
¿Cómo lo hacemos?  
Tendremos que calcular los 4 determinantes de orden 3 para comprobar si hay alguno diferente de 0 y el rango de B es 3.  
Eso sí, el que coincide con la matriz A no hace falta que lo calcule porque ya lo tengo calculado.</style>

In [46]:
import numpy as np
B=([
    [-2,1,0],
    [2,-8,8],
    [5,9,-9]
])
detB=np.linalg.det(B)
detB

58.000000000000036

In [47]:
import numpy as np
B=([
    [1,1,0],
    [0,-8,8],
    [-4,9,-9]
])
detB=np.linalg.det(B)
detB

-31.999999999999986

In [48]:
import numpy as np
B=([
    [1,-2,0],
    [0,2,8],
    [-4,5,-9]
])
detB=np.linalg.det(B)
detB

6.0

<span style="color:orange"> ¿Todo esto era necesario? NO!!!! ¿Por qué?  
Porque A es uno de los 4 determinantes de orden 3 de B y ya sabíamos que era diferente de 0, por lo que ya teníamos uno que cumplía lo que necesitábamos.</style>   

Si el determinante de la **matriz de coeficientes** es distinto de 0, nos encontramos con un SCD.

<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.</style>  
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [49]:
import numpy as np
A=([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
detA=np.linalg.det(A)
round(detA)

0.0

<span style="color:orange"> Da 0, por lo que A no tiene rango 3. Para ver si tiene rango 2, buscamos un determinante de orden 2x2 que sea diferente de 0.</style>

In [50]:
import numpy as np
A=([
    [0,1],
    [2,-3]
])
detA=np.linalg.det(A)
round(detA)

-2.0

<span style="color:orange"> Por lo que A tiene rango 2.  
¿Qué ocurre con B?</style>

In [51]:
import numpy as np
B=([
    [1,-4,8],
    [-3,2,1],
    [-8,7,1]
])
detA=np.linalg.det(B)
round(detB)

6.0

In [52]:
import numpy as np
B=([
    [0,-4,8],
    [2,2,1],
    [5,7,1]
])
detA=np.linalg.det(B)
round(detB)

6.0

In [53]:
import numpy as np
B=([
    [0,1,8],
    [2,-3,1],
    [5,-8,1]
])
detA=np.linalg.det(B)
round(detB)

6.0

<span style="color:orange"> Luego el rango de B es 3.  
Como tienen distinto rango, el sistema es incompatible, es decir, no tiene solución.</style>  

<span style="color:orange"> Ejemplo:  
Vamos a calcular si tiene solución el siguiente sistema de ecuaciones usando Python.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [54]:
import numpy as np
A=([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
detA=np.linalg.det(A)
round(detA)

-0.0

In [55]:
import numpy as np
A=([
   [1,0],
   [2,3]
])
detA=np.linalg.det(A)
round(detA)

3.0

<span style="color:orange"> Luego el rango de A es 2.  
¿Qué ocurre con B?</style>  

In [56]:
import numpy as np
B=([
    [0,1,2],
    [3,1,3],
    [3,2,5]
])
detB=np.linalg.det(B)
round(detB)

0.0

In [57]:
import numpy as np
B=([
    [1,1,2],
    [2,1,3],
    [3,2,5]
])
detB=np.linalg.det(B)
round(detB)

0.0

In [58]:
import numpy as np
B=([
    [1,0,2],
    [2,3,3],
    [3,3,5]
])
detB=np.linalg.det(B)
round(detB)

-0.0

<span style="color:orange"> Luego el rango de B es 2.  
Como coinciden y es menor que el número de incógnitas, es un SCI, es decir, tiene infinitas soluciones.</style>  

<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

## ¿Cómo calculamos la solución en caso de que exista?  

**Método de la matriz inversa**  

Dada A $\cdot$ X = B, entonces X=A<sup>-1</sup> $\cdot$ B

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de la matriz inversa.  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [64]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
   ])
B=([
    [0],[8],[-9]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[ 29.],
        [ 16.],
        [  3.]])

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de la matriz inversa. </style>
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [65]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
   ])
B=([
    [8],[1],[1]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[ -9.00719925e+15],
        [ -7.20575940e+15],
        [ -1.80143985e+15]])

<span style="color:orange">Sabíamos que no tenía solución y si nos fijamos los números que devuelve son enormes para el rango en que estamos trabajando, es como si fuesen "infinito".</style>

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de la matriz inversa.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [66]:
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
   ])
B=([
    [2],[3],[5]
])
inv_A=np.linalg.inv(A)
inv_A*B

matrix([[ 0. ],
        [-0.5],
        [ 0. ]])

<span style="color:orange"> En este caso me devuelve una solución válida, pero no todas las posibles.  
¿Cómo haríamos para calcular todas las posibles?  
El método más general es la reducción gaussiana:  
$
  A=
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   2 & 3 & 1 & 3\\
   3 & 3 & 2 & 5\\
  \end{array} } \right]
$  =  $
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   0 & 3 & -1 & -1\\
   0 & 3 & -1 & -1\\
  \end{array} } \right]
$ = $
  \left[ {\begin{array}{cc}
   1 & 0 & 1 & 2\\
   0 & 3 & -1 & -1\\
   0 & 0 & 0 & 0\\
  \end{array} } \right]
$  
Lo que se traduce en:  </style>
><span style="color:orange"> x<sub>1</sub>+x<sub>3</sub>=2</style>  
><span style="color:orange"> 3x<sub>2</sub>-x<sub>3</sub>=-1</style>  

<span style="color:orange"> Como comparten el x<sub>3</sub>, x<sub>3</sub>=$\lambda$.  
Luego la solución queda:  
> <span style="color:orange">x<sub>1</sub> = 2-$\lambda$</style>    
> <span style="color:orange">x<sub>2</sub> = $\frac{-1+\lambda}{3}$</style>    
> <span style="color:orange">x<sub>3</sub>=$\lambda$</style>    

**Método de Cramer**

Dada A $\cdot$ X = B, entonces:
* x=$\frac{A_x}{detA}$  
* y=$\frac{A_y}{detA}$  
* z=$\frac{A_z}{detA}$  

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de Cramer.  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>


In [67]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
   ])
AX=([
    [0,-2,1],
    [8,2,-8],
    [-9,5,9]
])
AY=([
    [1,0,1],
    [0,8,-8],
    [-4,-9,9]
])
AZ=([
    [1,-2,0],
    [0,2,8],
    [-4,5,-9]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X

[29.0, 16.0, 3.0]

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de Cramer. </style>
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [68]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
   ])
AX=([
    [8,1,-4],
    [1,-3,2],
    [1,-8,7]
])
AY=([
    [0,8,-4],
    [2,1,2],
    [5,1,7]
])
AZ=([
    [0,1,8],
    [2,-3,1],
    [5,-8,1]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X

[-9007199254740938.0, -7205759403792747.0, -1801439850948190.0]

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Python y el método de Cramer.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [69]:
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
   ])
AX=([
    [2,0,1],
    [3,3,1],
    [5,3,2]
])
AY=([
    [1,2,1],
    [2,3,1],
    [3,5,2]
])
AZ=([
    [1,0,2],
    [2,3,3],
    [3,3,5]
])
x=np.linalg.det(AX)/np.linalg.det(A)
y=np.linalg.det(AY)/np.linalg.det(A)
z=np.linalg.det(AZ)/np.linalg.det(A)
X=([round(x),round(y),round(z)])
X

[-5.0, 0.0, 3.0]

En Python, hay una manera directa de resolverlo.

<span style="color:orange"> Ejemplo:  
</style>  
> <span style="color:orange">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:orange">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:orange">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [70]:
import numpy as np

A = np.matrix(
    [[1,-2,1],
    [0,2,-8],
    [-4,5,9]]
)

B = np.matrix(
    [[0],
     [8],
     [-9]]
)

X = np.linalg.solve(A, B)
X

matrix([[ 29.],
        [ 16.],
        [  3.]])

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando NumPy.  </style>   
> <span style="color:orange">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:orange">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:orange">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [71]:
import numpy as np

A = np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])

B = np.matrix(
    [[8],
     [1],
     [1]]
)

X = np.linalg.solve(A, B)
X

matrix([[ -9.00719925e+15],
        [ -7.20575940e+15],
        [ -1.80143985e+15]])

<span style="color:orange"> Como podemos ver, no vale porque devuelve solución cuando no la hay.</style>    

<span style="color:orange"> Ejemplo:  
Calculemos la solución del siguiente sistema de ecuaciones usando Numpy.</style>  
> <span style="color:orange">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:orange">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:orange">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [72]:
import numpy as np

A = np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])

B = np.matrix(
    [[2],
     [3],
     [5]]
)

X = np.linalg.solve(A, B)
X

matrix([[-0.5],
        [ 0.5],
        [ 2.5]])

<span style="color:orange"> Como podemos ver, no vale porque devuelve una solución cuando sabemos que hay infinitas.  
Hay un método especial para esto en Python:</style>

In [3]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x,y,z
A=Matrix([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])
solve_linear_system(A,x,y,z)

{y: z/3 - 1/3, x: -z + 2}