# 4. Matrices

# Introducción
## Modelos de computadora en el diseño de aviones

Para diseñar la siguiente generación de aviones comerciales y militares, los ingenieros de Phantom Works de Boeing usan el modelado en tres dimensiones y la dinámica de  uidos basada en computadora (CFD, del inglés computational  uid dynamics).  
Estos profesionales estudian cómo se desplaza el flujo de aire alrededor de un avión virtual para dar respuesta a importantes preguntas sobre el diseño antes de crear modelos físicos.  
El procedimiento ha reducido en forma drástica los tiempos y costos del ciclo de diseño ,y el álgebra lineal desempeña un papel de gran importancia en el proceso.  
El avión virtual comienza como un modelo “de alambre” matemático que existe sólo en la memoria de la computadora y en las terminales de despliegue gráfico.  
![No se puede mostrar](http://www.abc.es/Media/201510/22/iberia-boeing-474--644x430.jpg)
Este modelo matemático organiza e influye en cada paso del diseño y la fabricación del avión ,tanto en el exterior como en el interior.  
El análisis de CFD tiene que ver con la superficie externa.
Aunque el acabado del forro de un avión puede parecer suave, la geometría de la superficie es complicada. Además de alas y fuselaje, un avión tiene barquillas, estabilizadores, tablillas, aletas y alerones.  
La forma en que el aire fluye alrededor de estas estructuras determina cómo se mueve el avión en el cielo. Las ecuaciones que describen el flujo del aire son complicadas, y deben tener en cuenta la admisión de los motores, los gases despedidos por éstos, y las estelas que dejan las alas del avión.  
Para estudiar el flujo del aire, los ingenieros necesitan de una descripción muy depurada de la superficie del avión.
Una computadora crea un modelo de la superficie al superponer, primero, una malla tridimensional de “cuadros” sobre el modelo de alambre original.   
En esta malla, los cuadros caen completamente dentro o completamente fuera del avión, o intersecan la superficie del mismo.  
La computadora selecciona los cuadros que intersecan la superficie y los subdivide, reteniendo sólo aquellos más pequeños que aún intersecan la superficie. El proceso de subdivisión se repite hasta que la malla se vuelve extremadamente fina.  
Una malla típica puede incluir más de 400,000 cuadros.
El proceso para encontrar el flujo de aire alrededor del avión implica la resolución repetida de un sistema de ecuaciones lineales A$\cdot$**x** = **b** que puede involucrar hasta2 millones de ecuaciones y variables.  
El vector **b** cambia a cada momento, con base en datos provenientes de la malla y de las soluciones de ecuaciones previas.  
Con el uso de computadoras comerciales más rápidas, un equipo de Phantom Works puede emplear desde unas cuantas horas hasta varios días para con gurar y resolver un solo problema de flujo de aire.  
Después, el equipo analiza la solución, puede hacer pequeños cambios a la superficie del avión, y comienza de nuevo con todo el proceso.  
Pueden requerirse miles de corridas de CFD.  
![No se puede mostrar](https://3dwarehouse.sketchup.com/warehouse/getpubliccontent?contentId=e79e758a-7094-4d4c-b316-0e2782b883ef)
En la actualidad, la CFD ha revolucionado el diseño de alas. El Boeing Blended Wing Body se encuentra en diseño para ser producido a más tardar en el año 2020.  
Se presentan dos conceptos importantes que ayudan en la resolución de los enormes sistemas de ecuaciones de este tipo:
* *Matrices partidas*: Un sistema de ecuaciones típico de CFD tiene una matriz de coeficientes “dispersa o rala” con entradas que en su mayoría son iguales a cero.  
El agrupamiento correcto de las variables conduce a una matriz partida con muchos bloques de ceros.  
* *Factorizaciones de matrices*: Aunque el sistema esté escrito con matrices partidas, sigue siendo complicado.  
Para simplificar aún más los cálculos, el programa computacional de CFD aplicado en Boeing utiliza lo que se conoce como factorización LU de la matriz de coeficientes.  

Para analizar la solución de un sistema de flujo de aire, los ingenieros desean visualizar cómo fluye el aire sobre la superficie del avión. Los ingenieros utilizan gráficas y el álgebra lineal proporciona el método para elaborarlas.  
El modelo de alambre de la superficie del avión se almacena como datos en muchas matrices.  
Una vez que la imagen se despliega en una pantalla de computadora, los ingenieros pueden escalarla, acercar
y alejar regiones pequeñas, y girarla para ver partes que pudieran quedar ocultas en determinado ángulo.  
Cada una de estas operaciones se realiza mediante una multiplicación de matrices adecuada. 

## ¿Qué es una matriz?

Si A es una matriz m × n, esto es, una matriz con m  las y n columnas, entonces la entrada escalar en la i-ésima  la y la j-ésima columna de A se denota mediante aij y se llama entrada (i, j) de A.  
$
  M=
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1j}  \\
   a_{21} & a_{22}  & ... & a_{2j}  \\
   ... & ...  & ... & ...  \\
   a_{i1} & a_{i2}  & ... & a_{ij}  \\
  \end{array} } \right]
$  
Las entradas diagonales en una matriz m × n A = [aij] son a<sub>11</sub>, a<sub>22</sub>, a<sub>33</sub>, ... , y forman la **diagonal principal** de A.  
Una **matriz diagonal** es una matriz cuadrada cuyas entradas no diagonales son cero.  
Un ejemplo es la matriz identidad n × n, I<sub>n</sub>.  
$
  I_n=
  \left[ {\begin{array}{cc}
   1 & 0  & ... & 0  \\
   0 & 1  & ... & 0  \\
   ... & ...  & ... & ...  \\
   0 & 0  & ... & 1  \\
  \end{array} } \right]
$  
Una matriz de m × n cuyas entradas son todas cero es una **matriz cero** y se escribe como 0. El tamaño de 0, por lo general, resulta evidente a partir del contexto.  

La representación en Python puede venir dada de varias maneras diferentes. Nosotros vamos a ver:  
* Arrays  
* Matrices  

NOTA: Las ventajas de usar matrices en el fondo son muy pocas y además la mayoría de funciones de NumPy maneja arrays, así que tendrías que convertir entre ambos tipos constantemente. Vamos a mostrar brevemente el uso de las matrices también, pero mejor utilizar arrays y olvidarse.


<span style="color:orange"> Ejemplo: Escribamos en Python la siguiente matriz: 
$
  A=
  \left[ {\begin{array}{cc}
   1 & 2  & 3   \\
   10 & 20  & 30   \\
  \end{array} } \right]
$.  
Primero con matrices:</style> 

In [1]:
import numpy as np
np.matrix([
   [1, 2, 3],
   [10, 20, 30]
   ])

matrix([[ 1,  2,  3],
        [10, 20, 30]])

<span style="color:orange">Ahora con arrays:</style> 

In [2]:
import numpy as np
A = np.array([[1, 2,3], [10,20,30]])
A

array([[ 1,  2,  3],
       [10, 20, 30]])

<span style="color:orange"> Ejemplo: Ahora queremos generar la matriz identidad de orden 4
</style> 

In [3]:
import numpy as np
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

<span style="color:orange"> Ejemplo: Escribamos en Python la matriz de 4x3 con unos en una diagonal y ceros en el resto de elementos/style> 

In [4]:
import numpy as np
np.eye(4, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

<span style="color:orange"> Con el siguiente parámetro podemos controlar qué diagonal se rellena.</style> 

In [5]:
import numpy as np
np.eye(4, 3,k=-1)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<span style="color:orange"> Ejemplo: Ahora queremos generar la matriz cero de orden 4
</style> 

In [6]:
import numpy as np
A = np.zeros((4, 4))
A

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Suma de matrices

* Se dice que dos **matrices** son **iguales** si tienen el mismo tamaño, es decir, el mismo número de filas y de columnas, y sus columnas correspondientes son iguales.  
* Si A y B son matrices m × n, entonces la suma A + B es la matriz m × n cuyas columnas son las sumas de las columnas correspondientes de A y B. Como la suma vectorial de las columnas se realiza por entradas, cada entrada en A + B es la suma de las entradas correspondientes de A y B. 
* La suma A + B está definida sólo cuando A y B son del mismo tamaño.  

<span style="color:orange"> Ejemplo: Queremos sumar las matrices $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ y $
  matriz2=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$.  
Primero con Numpy:</style> 

In [7]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.matrix(
    [[-1, 2],
     [1, -2]]
)

matriz1 + matriz2

matrix([[ 0,  6],
        [ 3, -2]])

<span style="color:orange"> Ahora con arrays:</style> 

In [8]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

matriz1 + matriz2

array([[ 0,  6],
       [ 3, -2]])

## Multiplicación de una matriz por un escalar

* Si r es un escalar y A es una matriz, entonces el múltiplo escalar rA es la matriz cuyas columnas son r veces las columnas correspondientes de A. 
* Al igual que con los vectores, se de ne −A como (−1)A y se escribe A − B en lugar de A + (−1)B.

<span style="color:orange"> Ejemplo: Queremos multiplicar la $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ por 2.  
Primero con matrices:
</style>

In [9]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

2*matriz1

matrix([[2, 8],
        [4, 0]])

<span style="color:orange"> Ahora con arrays:</style> 

In [10]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

2*matriz1

array([[2, 8],
       [4, 0]])

## Multiplicación matricial

Si A es una matriz m × n, y si B es una matriz n × p con columnas b<sub>1</sub>, ... , b<sub>p</sub>, entonces el **producto** AB es la matriz m × p cuyas columnas son Ab<sub>1</sub>, ... , Ab<sub>p</sub>.
Esto es,
> AB = A [ b<sub>1</sub> b<sub>2</sub> ... b<sub>p</sub> ] = [ Ab<sub>1</sub> Ab<sub>2</sub> ... Ab<sub>p</sub> ]  
Más explícitamente:
A*B= $
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{m1} & a_{m2}  & ... & a_{mn}  \\
  \end{array} } \right]
$ * $
  \left[ {\begin{array}{cc}
   b_{11} & b_{12}  & ... & b_{1p}  \\
   b_{21} & b_{22}  & ... & b_{2p}  \\
   ... & ...  & ... & ...  \\
   b_{n1} & b_{n2}  & ... & b_{np}  \\
  \end{array} } \right]
$ = $
  \left[ {\begin{array}{cc}
   a_{11}\cdot b_{11}+ a_{12}\cdot b_{21} + ... + a_{1n}\cdot b_{n1}& a_{11}\cdot b_{12}+ a_{12}\cdot b_{22} + ... + a_{1n}\cdot b_{n2}  & ... & a_{11}\cdot b_{1p}+ a_{12}\cdot b_{2p} + ... + a_{1n}\cdot b_{np}  \\
   a_{21}\cdot b_{11}+ a_{22}\cdot b_{21} + ... + a_{2n}\cdot b_{n1}& a_{21}\cdot b_{12}+ a_{22}\cdot b_{22} + ... + a_{2n}\cdot b_{n2}  & ... & a_{21}\cdot b_{1p}+ a_{22}\cdot b_{2p} + ... + a_{2n}\cdot b_{np}  \\
   ... & ...  & ... & ...  \\
      a_{m1}\cdot b_{11}+ a_{m2}\cdot b_{21} + ... + a_{mn}\cdot b_{n1}& a_{m1}\cdot b_{12}+ a_{m2}\cdot b_{22} + ... + a_{mn}\cdot b_{n2}  & ... & a_{m1}\cdot b_{1p}+ a_{m2}\cdot b_{2p} + ... + a_{mn}\cdot b_{np}  \\
  \end{array} } \right]
$  

<span style="color:orange"> Ejemplo: Queremos multiplicar las matrices $
  matriz1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$ y $
  matriz2=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$.  
Primero con matrices:</style> 

In [11]:
import numpy as np

matriz1 = np.matrix(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.matrix(
    [[-1, 2],
     [1, -2]]
)

matriz1 * matriz2

matrix([[ 3, -6],
        [-2,  4]])

<span style="color:orange"> Ahora con arrays:</style> 

In [12]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

matriz1 * matriz2

array([[-1,  8],
       [ 2,  0]])

<span style="color:orange"> Si nos fijamos, no coincide con el anterior resultado. Aquí una diferencia entre trabajar con arrays y con matrices.  
El asterisco con arrays es multiplicación elemento aelemento. Si lo que queremos, como es el caso, es hacer la multiplicación matrical, tenemos que usar dot:</style> 

In [13]:
import numpy as np

matriz1 = np.array(
    [[1, 4],
     [2, 0]]
)

matriz2 = np.array(
    [[-1, 2],
     [1, -2]]
)

np.dot(matriz1,matriz2)

array([[ 3, -6],
       [-2,  4]])

#### Advertencias

* En general, AB ≠ BA.  

<span style="color:orange"> Ejemplo: Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   5 & 1 \\
   3 & -2\\
  \end{array} } \right]
$ y $
  B=
  \left[ {\begin{array}{cc}
   2 & 0 \\
   4 & 3\\
  \end{array} } \right]
$, queremos calcular AB y BA.</style> 

In [14]:
import numpy as np

matriz1 = np.matrix(
    [[5, 1],
     [3, -2]]
)

matriz2 = np.matrix(
    [[2, 0],
     [4, 3]]
)

matriz1 * matriz2

matrix([[14,  3],
        [-2, -6]])

In [15]:
import numpy as np

matriz1 = np.matrix(
    [[5, 1],
     [3, -2]]
)

matriz2 = np.matrix(
    [[2, 0],
     [4, 3]]
)

matriz2 * matriz1

matrix([[10,  2],
        [29, -2]])

* Si AB = AC, en general no es cierto que B = C.  

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

## Traspuesta de una matriz

Dada una matriz A de m × n, la transpuesta de A es la matriz n × m, denotada mediante A<sup>T</sup>, cuyas columnas se forman a partir de las filas correspondientes de A.

<span style="color:orange"> Ejemplo: Dada la matriz $
  A=
  \left[ {\begin{array}{cc}
   5 & 1 & 7\\
   3 & -2 & 5\\
  \end{array} } \right]
$ , su matriz traspuesta es $
  A^T=
  \left[ {\begin{array}{cc}
   5 & 3 \\
   1 & -2\\
   7 & 5\\
  \end{array} } \right]
$.  
¿Cómo lo haríamos en Python?  
Primero con matrices:</style> 

In [18]:
import numpy as np
A=np.matrix([
   [5,1,7],
   [3,-2,5]
   ])
AT=np.transpose(A)
AT

matrix([[ 5,  3],
        [ 1, -2],
        [ 7,  5]])

<span style="color:orange"> Ahora con arrays:</style> 

In [19]:
import numpy as np
A=np.array([
   [5,1,7],
   [3,-2,5]
   ])
AT=np.transpose(A)
AT

array([[ 5,  3],
       [ 1, -2],
       [ 7,  5]])

## Matriz inversa (usando Gauss)

Al igual que el inverso de 5 es $\frac{1}{5}$ = 5<sup>-1</sup>, dada la matriz A, no puedo calcular $\frac{1}{A}$, pero sí A<sup>-1</sup>.  
La manera usual de calcular la matriz inversa, sobre todo si no es demasiado grande, es mediante determinantes (lo veremos posteriormente), pero hay otro modo general de calcular la matriz inversa, que es con el método de Gauss:  
* Dada una matriz A, considero la matriz (A|I)
* Mediante una serie de transformaciones tengo que conseguir transformarla en (I|B)
* B=A<sup>-1</sup>  

<span style="color:orange"> Ejemplo: Vamos a encontrar la inversa de  $
  A=
  \left[ {\begin{array}{cc}
   0 & 1 & 2\\
   1 & 0 & 3\\
   4 & -3 & 8\\
  \end{array} } \right]
$  usando el método de Gauss</style> 

In [20]:
import numpy as np
A_I=np.array([
   [0,1,2,1,0,0],
   [1,0,3,0,1,0],
   [4,-3,8,0,0,1]
   ])
A_I

array([[ 0,  1,  2,  1,  0,  0],
       [ 1,  0,  3,  0,  1,  0],
       [ 4, -3,  8,  0,  0,  1]])

<span style="color:orange"> Lo primero que hacemos es intercambiar la segunda fila con la primera fla</style> 

In [21]:
A_I_paso1=(
    A_I[1],A_I[0],A_I[2])
A_I_paso1

(array([1, 0, 3, 0, 1, 0]),
 array([0, 1, 2, 1, 0, 0]),
 array([ 4, -3,  8,  0,  0,  1]))

<span style="color:orange"> Se ha convertido en un array de arrays, pero nosotros queremos un único array.  
Veamos cómo hacerlo.</style> 

In [22]:
A_I_paso1=np.append([A_I[1]],[A_I[0]],0)
A_I_paso1

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [23]:
A_I_paso1=np.vstack([A_I_paso1,[A_I[2]]])
A_I_paso1

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 4, -3,  8,  0,  0,  1]])

<span style="color:orange"> Queremos hacer 0 el elemento de la posición 31 (20 para Python).</style> 

In [24]:
A_I_paso2=np.append([A_I_paso1[0]],[A_I_paso1[1]],0)
A_I_paso2

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [25]:
A_I_paso2=np.vstack([A_I_paso2,[A_I_paso1[2]-4*A_I_paso1[0]]])
A_I_paso2

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0, -3, -4,  0, -4,  1]])

<span style="color:orange"> Queremos hacer 0 el elemento de la posición 32 (21 para Python).</style> 

In [26]:
A_I_paso3=np.append([A_I_paso2[0]],[A_I_paso2[1]],0)
A_I_paso3

array([[1, 0, 3, 0, 1, 0],
       [0, 1, 2, 1, 0, 0]])

In [27]:
A_I_paso3=np.vstack([A_I_paso3,[A_I_paso2[2]+3*A_I_paso2[1]]])
A_I_paso3

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0,  0,  2,  3, -4,  1]])

<span style="color:orange"> Queremos hacer 0 el elemento de la posición 13 (02 para Python).</style> 

In [28]:
A_I_paso4=np.array([A_I_paso3[0]-(3/2)*A_I_paso3[2]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5]])

In [29]:
A_I_paso4=np.vstack([A_I_paso4,[A_I_paso3[1]]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ]])

In [30]:
A_I_paso4=np.vstack([A_I_paso4,[A_I_paso3[2]]])
A_I_paso4

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

<span style="color:orange"> Queremos hacer 0 el elemento de la posición 23 (02 para Python).</style> 

In [31]:
A_I_paso5=np.append([A_I_paso4[0]],[A_I_paso4[1]-A_I_paso4[2]],0)
A_I_paso5

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ]])

In [32]:
A_I_paso5=np.vstack([A_I_paso5,[A_I_paso4[2]]])
A_I_paso5

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

<span style="color:orange"> Queremos hacer 0 el elemento de la posición 33 (02 para Python).</style> 

In [33]:
A_I_paso6=np.append([A_I_paso5[0]],[A_I_paso5[1]],0)
A_I_paso6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ]])

In [34]:
A_I_paso6=np.vstack([A_I_paso6,[(1/2)*A_I_paso5[2]]])
A_I_paso6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

<span style="color:orange"> Luego la matriz inversa queda:</style> 

In [35]:
inv_A=np.transpose(np.vstack([A_I_paso6[:,3],A_I_paso6[:,4],A_I_paso6[:,5]]))
inv_A

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

<span style="color:orange"> Sorpresa! Se puede hacer directamente:</style> 
    
![No se puede mostrar](Images/giphy-9-6.gif)    

In [36]:
import numpy as np
A=np.matrix([
   [0,1,2],
   [1,0,3],
   [4,-3,8]
   ])

inv_A = np.linalg.inv(A)
inv_A

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [37]:
import numpy as np
A=np.array([
   [0,1,2],
   [1,0,3],
   [4,-3,8]
   ])

inv_A = np.linalg.inv(A)
inv_A

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

## Rango de una matriz

El rango de una matriz se define como el número de vectores linealmente independientes que la componen.  
Siempre va a ser menor o igual que el menor de las cantidades número_filas y número_columnas.  

<span style="color:orange"> Ejemplo: Vamos a calcular el rango de  $
  A=
  \left[ {\begin{array}{cc}
   2 & 5 & -3 & -4 & 8\\
   4 & 7 & -4 & -3 & 9\\
   6 & 9 & -5 & 2 & 4\\
   0 & -9 & 6 & 5 & -6\\
  \end{array} } \right]
$  </style> 


In [38]:
import numpy as np
A=np.matrix([
   [2,5,-3,-4,8],
   [4,7,-4,-3,9],
   [6,9,-5,2,4],
   [60,-9,6,5,-6]
   ])
A

matrix([[ 2,  5, -3, -4,  8],
        [ 4,  7, -4, -3,  9],
        [ 6,  9, -5,  2,  4],
        [60, -9,  6,  5, -6]])

<span style="color:orange"> Queremos hacer 0 los elementos de la primera columna salvo el de la primera fila.</style> 

In [39]:
A_paso1=np.vstack([A[0],A[1]-2*A[0]])
A_paso1

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7]])

In [40]:
A_paso1=np.vstack([A_paso1,A[2]-3*A[0]])
A_paso1

matrix([[  2,   5,  -3,  -4,   8],
        [  0,  -3,   2,   5,  -7],
        [  0,  -6,   4,  14, -20]])

In [41]:
A_paso1=np.vstack([A_paso1,A[3]-10*A[2]])
A_paso1

matrix([[  2,   5,  -3,  -4,   8],
        [  0,  -3,   2,   5,  -7],
        [  0,  -6,   4,  14, -20],
        [  0, -99,  56, -15, -46]])

<span style="color:orange"> Queremos hacer 0 los elementos de la segunda columna exceptuando las dos primeras filas.</style>

In [42]:
A_paso2=np.vstack([A_paso1[0],A_paso1[1]])
A_paso2

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7]])

In [43]:
A_paso2=np.vstack([A_paso2,A_paso1[2]-2*A_paso1[1]])
A_paso2

matrix([[ 2,  5, -3, -4,  8],
        [ 0, -3,  2,  5, -7],
        [ 0,  0,  0,  4, -6]])

In [44]:
A_paso2=np.vstack([A_paso2,A_paso1[3]-33*A_paso1[1]])
A_paso2

matrix([[   2,    5,   -3,   -4,    8],
        [   0,   -3,    2,    5,   -7],
        [   0,    0,    0,    4,   -6],
        [   0,    0,  -10, -180,  185]])

<span style="color:orange"> Queremos hacer 0 el elemento 43.  
Si intercambio la fila 3 con la 4 ya lo tendría:</style>

In [45]:
A_paso3=np.vstack([A_paso2[0],A_paso2[1]])
A_paso3=np.vstack([A_paso3,A_paso2[3]])
A_paso3=np.vstack([A_paso3,A_paso2[2]])
A_paso3

matrix([[   2,    5,   -3,   -4,    8],
        [   0,   -3,    2,    5,   -7],
        [   0,    0,  -10, -180,  185],
        [   0,    0,    0,    4,   -6]])

<span style="color:orange"> Luego RangoA=4.  
¿Alguna manera directa desde Python?</style>

In [46]:
import numpy as np
A=np.matrix([
   [2,5,-3,-4,8],
   [4,7,-4,-3,9],
   [6,9,-5,2,4],
   [60,-9,6,5,-6]
   ])
np.linalg.matrix_rank(A)

4