# 11. Eliminación Gaussiana

# ¿Para qué sirve la eliminación gaussiana?

* Encontrar una base para el espacio generador dados ciertos vectores. Esto también nos proporciona un algoritmo para el rango y, por lo tanto, para probar la dependencia lineal.  
* Resolver una ecuación matricial, que es lo mismo que expresar un vector dado como una combinación lineal de otros vectores dados, que es lo mismo que resolver un sistema de ecuaciones lineales.  
* Encontrar una base para el espacio nulo de una matriz, que es lo mismo que encontrar una base para el conjunto de soluciones de un sistema lineal homogéneo, que también es importante para representar el conjunto de soluciones de un sistema lineal general.  

# Forma escalonada  

La **forma escalonada** es la generalización de las matrices triangulares.  

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 1 & 2 \\
   0 & 0 & 0  & 0 & 0 & 6 \\
  \end{array} } \right]
$ está en forma escalonada.  
Fijemos en:</style>  
* <span style="color:orange"> La primera entrada distinta de cero en la fila 1 está en la columna 2.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 2 está en la columna 3.</style>   
* <span style="color:orange"> La primera entrada distinta de cero en la fila 3 está en la columna 5.</style>     * <span style="color:orange"> La primera entrada distinta de cero en la fila 4 está en la columna 6.</style>   
Una matriz A mxn está en **forma escalonada** si cumple la siguiente condición:  
para cualquier fila, si la primera entrada distinta de cero de esa fila está en la posición k, la primera entrada distinta de cero de cada fila anterior está en una posición menor que k.  

Esta definición implica que, a medida que recorre las filas de A, las primeras entradas distintas de cero se mueven estrictamente a la derecha, formando una especie de escalera que desciende a la derecha.  

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   4 & 1  & 3 & 0  \\
   0 & 3  & 0 & 1  \\
   0 & 0  & 1 & 7  \\
   0 & 0 & 0  & 9  \\
  \end{array} } \right]
$ está en forma escalonada.  </style>  

Si una fila de una matriz en forma escalonada es cero, cada fila subsiguiente también debe ser cero.  

<span style="color:orange"> Ejemplo:  
La matriz $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 0 & 0 \\
   0 & 0 & 0  & 0 & 0 & 0 \\
  \end{array} } \right]
$ está en forma escalonada.  </style>   

¿De qué sirve tener una matriz en forma escalonada?  
Si una matriz está en forma escalonada, las filas distintas de cero forman una base para el espacio filas.  

<span style="color:orange"> Ejemplo:  
Una base para el espacio filas de $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 0 & 0 \\
   0 & 0 & 0  & 0 & 0 & 0 \\
  \end{array} } \right]
$ es {[0,2,3,0,5,6],[0,1,0,3,4]}.</style>  

<span style="color:orange"> Ejemplo:  
Si todas las filas son diferentes de cero, como en $
  M=
  \left[ {\begin{array}{cc}
   0 & 2  & 3 & 0 & 5 & 6 \\
   0 & 0  & 1 & 0 & 3 & 4 \\
   0 & 0  & 0 & 0 & 1 & 2 \\
   0 & 0 & 0  & 0 & 0 & 6 \\
  \end{array} } \right]
$, el espacio filas estará formado por todas las filas.</style>  

Si la matriz está en forma escalonada, las filas distintas de cero forman una base para el espacio de fila.  

# Algoritmo para transformar una matriz en una matriz escalonada  

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:orange"> Ejemplo:  
$\left[ {\begin{array}{cc}
   2 & 1 & 1\\
   1 & 2 & 1\\
   1 & 1 & 2\\
  \end{array} } \right] = \left[ {\begin{array}{cc}
   1 & 0 & 0\\
   \frac{1}{2} & 1 & 0\\
   \frac{1}{2} & \frac{1}{3} & 2\\
  \end{array} } \right] \left[ {\begin{array}{cc}
   2 & 1 & 1\\
   0 & \frac{3}{2} & \frac{1}{2}\\
   0 & 0 & \frac{4}{3}\\
  \end{array} } \right]$  
  Con Scipy:</style>

In [10]:
from numpy import matrix
from scipy import linalg
A=matrix([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
p,l,u=linalg.lu(A)
p

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.5       ,  0.33333333,  1.        ]])

In [12]:
u

array([[ 2.        ,  1.        ,  1.        ],
       [ 0.        ,  1.5       ,  0.5       ],
       [ 0.        ,  0.        ,  1.33333333]])

<span style="color:orange"> Ejemplo:  
$\left[ {\begin{array}{cc}
   2 & 1 & 1\\
   1 & 2 & 1\\
   1 & 1 & 2\\
  \end{array} } \right] = \left[ {\begin{array}{cc}
   1 & 0 & 0\\
   \frac{1}{2} & 1 & 0\\
   \frac{1}{2} & \frac{1}{3} & 2\\
  \end{array} } \right] \left[ {\begin{array}{cc}
   2 & 1 & 1\\
   0 & \frac{3}{2} & \frac{1}{2}\\
   0 & 0 & \frac{4}{3}\\
  \end{array} } \right]$  
  Con Sympy:</style>

In [13]:
from sympy import Matrix
A=Matrix([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
l,u,p=A.LUdecomposition()
l

Matrix([
[  1,   0, 0],
[1/2,   1, 0],
[1/2, 1/3, 1]])

In [14]:
u

Matrix([
[2,   1,   1],
[0, 3/2, 1/2],
[0,   0, 4/3]])